name: build binaries

on:
  workflow_call:
    inputs:
      tag:
        description: "tag for the containers"
        default: ""
        required: true
        type: string
jobs:
  binaries:
    name: build binaries
    permissions:
      contents: read
    env:
      GO111MODULE: on
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.0.0
        with:
          go-version: "^1.21"
      - name: build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 \
            go build -ldflags="-X 'main.Version=${{ inputs.tag }}' " \
              -o ./dist/gotf-extract-${{ inputs.tag }}_${{ matrix.os }}_${{ matrix.arch }} cmd/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: gotf-extract-${{ inputs.tag }}_${{ matrix.os }}_${{ matrix.arch }}
          path: ./dist/gotf-extract-${{ inputs.tag }}_${{ matrix.os }}_${{ matrix.arch }}
