name: build docker-image

on:
  workflow_call:
    inputs:
      tag:
        description: "tag for the containers"
        default: ""
        required: true
        type: string
      build_context:
        default: ./
        type: string
      dockerfile:
        default: ./Dockerfile
        type: string

jobs:
  docker:
    name: Build Docker image and push to github-registry
    permissions:
      contents: read
      packages: write
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github-Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push branch
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.build_context }}
          file: ./${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.tag }}
