name: build docker-image
on:
  push:
    branches:
      - master

jobs:
  docker:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_docker.yaml
    secrets: inherit
    with:
      tag: "latest"
      dockerfile: ./docker/alpine/Dockerfile

  package:
    uses: ./.github/workflows/_binary.yaml
    secrets: inherit
    with:
      tag: "latest"

  binary:
    needs: [package]
    uses: ./.github/workflows/_package.yaml
    secrets: inherit
    with:
      tag: "latest"
